--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DenielWorld/JasonDB
build-by-default: true
branches:
- master
projects:
  JasonDB:
    path: ""
    model: virion
    type: library
...
